#!/bin/bash
echo "total 12
-rwxr--r-- 1 root root 73 Jun  8 07:29 0-current_working_directory.sh
-rwxr--r-- 1 root root 60 Jun  8 07:50 1-listit.sh
-rwxr--r-- 1 root root 25 Jun  8 08:14 2-bring_me_home"
